export type Industry = {industry_name:string; stock_count:number; valid_stock_count:number; up_ratio:number; down_ratio:number; median_pct_chg:number; mean_pct_chg:number; gt_3_ratio:number; lt_minus_3_ratio:number; limit_up_count:number; limit_down_count:number; total_net_mf_amount:number; main_net_mf_amount:number; elg_net_mf_amount:number; lg_net_mf_amount:number; main_net_positive_ratio:number; resonance_score:number};
export type Review = {trade_date:string; market_state:string; price_state:string; moneyflow_state:string; risk_level:string; summary_text:string; valid_stock_count:number; universe_stock_count:number; data_coverage_ratio:number; up_count:number; down_count:number; flat_count:number; up_ratio:number; down_ratio:number; flat_ratio:number; median_pct_chg:number; mean_pct_chg:number; gt_3_count:number; lt_minus_3_count:number; gt_3_ratio:number; lt_minus_3_ratio:number; limit_up_count:number; limit_down_count:number; limit_calc_method:string; total_net_mf_amount:number; main_net_mf_amount:number; elg_net_mf_amount:number; lg_net_mf_amount:number; md_net_mf_amount:number; sm_net_mf_amount:number; main_net_positive_ratio:number; net_mf_positive_ratio:number; moneyflow_coverage_ratio:number; industry_resonance_top:Industry[]; industry_moneyflow_top:Industry[]; industry_price_width_top:Industry[]; industry_weak_top:Industry[]; universe_field_mapping?: Record<string, unknown>};

export type LimitupStock = {code:string; ts_code?:string; name:string; price:number; changePercent:number; amount:number; industry:string; streak:number; startDate?:string; startLabel?:string; endDate?:string; endLabel?:string; duration?:number; roles?:{type:string;label:string}[]; dataSource?:string};
export type LimitupRow = {date:string; label:string; limitUpCount:number; limitDownCount:number; limitUpScore:number; limitDownScore:number; mood:number; thirdBoardPlusCount:number; maxStreak:number; leaderNames:string; ladder:LimitupStock[]; candidatePool:LimitupStock[]};
export type LeaderSegment = {code:string; ts_code?:string; name:string; industry:string; startDate:string; startLabel:string; endDate:string; endLabel:string; startIndex:number; endIndex:number; duration:number; maxStreak:number};
export type LimitupReview = {updatedAt:string; source?:string; selectedDay:{date:string;label:string;limitUpCount:number;limitDownCount:number;emotionValue:number;thirdBoardPlusCount:number;maxStreak:number;leaderNames:string}; rows:LimitupRow[]; leaderSegments?:LeaderSegment[]; leaderSegmentsWindow?:LeaderSegment[]; emotionFormula:string; displayLimitations?:string; warning?:string};
export type StrongTrendItem = {rank:number; ts_code:string; code:string; name:string; industry:string; retYear:number; peakRetYear:number; retHalf:number; retQuarter:number; retMonth:number; ret10:number; drawdown:number; peakDate?:string; daysFromPeak?:number; ma20Distance?:number; ma60Distance?:number; ma20Slope?:number; ma60Slope?:number; highPosition?:number; recentAmplitude20?:number; trendLineType?:string; trendLineDistance?:number; trendLineTouched?:boolean; status:string; trendScore:number; latestClose:number; latestAmount:number};
export type StrongTrendKline = {date:string; open:number; high:number; low:number; close:number; amount:number; pct_chg:number};
export type StrongTrendReview = {source:string; tradeDate:string; startDate:string; endDate:string; periodDays:number; updatedAt:string; top:number; summary:{poolCount:number; industryCount:number; topName:string; topRetYear:number; topScore:number}; items:StrongTrendItem[]; industryDistribution:{industry:string; count:number; avgRetYear:number; avgPeakRetYear?:number; avgScore:number}[]; kline:Record<string, StrongTrendKline[]>; statusRule:string};
