export type Industry = {industry_name:string; stock_count:number; valid_stock_count:number; up_ratio:number; down_ratio:number; median_pct_chg:number; mean_pct_chg:number; gt_3_ratio:number; lt_minus_3_ratio:number; limit_up_count:number; limit_down_count:number; total_net_mf_amount:number; main_net_mf_amount:number; elg_net_mf_amount:number; lg_net_mf_amount:number; main_net_positive_ratio:number; resonance_score:number};
export type Review = {trade_date:string; market_state:string; price_state:string; moneyflow_state:string; risk_level:string; summary_text:string; valid_stock_count:number; universe_stock_count:number; data_coverage_ratio:number; up_count:number; down_count:number; flat_count:number; up_ratio:number; down_ratio:number; flat_ratio:number; median_pct_chg:number; mean_pct_chg:number; gt_3_count:number; lt_minus_3_count:number; gt_3_ratio:number; lt_minus_3_ratio:number; limit_up_count:number; limit_down_count:number; limit_calc_method:string; total_net_mf_amount:number; main_net_mf_amount:number; elg_net_mf_amount:number; lg_net_mf_amount:number; md_net_mf_amount:number; sm_net_mf_amount:number; main_net_positive_ratio:number; net_mf_positive_ratio:number; moneyflow_coverage_ratio:number; industry_resonance_top:Industry[]; industry_moneyflow_top:Industry[]; industry_price_width_top:Industry[]; industry_weak_top:Industry[]; universe_field_mapping?: Record<string, unknown>};

export type LimitupStock = {code:string; ts_code?:string; name:string; price:number; changePercent:number; amount:number; industry:string; streak:number; startDate?:string; startLabel?:string; endDate?:string; endLabel?:string; duration?:number; roles?:{type:string;label:string}[]; dataSource?:string};
export type LimitupRow = {date:string; label:string; limitUpCount:number; limitDownCount:number; limitUpScore:number; limitDownScore:number; mood:number; thirdBoardPlusCount:number; maxStreak:number; leaderNames:string; ladder:LimitupStock[]; candidatePool:LimitupStock[]};
export type LeaderSegment = {code:string; ts_code?:string; name:string; industry:string; startDate:string; startLabel:string; endDate:string; endLabel:string; startIndex:number; endIndex:number; duration:number; maxStreak:number};
export type LimitupReview = {updatedAt:string; source?:string; selectedDay:{date:string;label:string;limitUpCount:number;limitDownCount:number;emotionValue:number;thirdBoardPlusCount:number;maxStreak:number;leaderNames:string}; rows:LimitupRow[]; leaderSegments?:LeaderSegment[]; leaderSegmentsWindow?:LeaderSegment[]; emotionFormula:string; displayLimitations?:string; warning?:string};
export type StrongTrendItem = {rank:number; ts_code:string; code:string; name:string; industry:string; retYear:number|null; ret240?:number|null; retHalf:number|null; ret120?:number|null; retQuarter:number|null; ret60?:number|null; retMonth:number|null; ret20?:number|null; ret10:number|null; drawdown:number|null; drawdown60?:number|null; drawdown120?:number|null; highPos120?:number|null; amp20?:number|null; distMa20?:number|null; distMa60?:number|null; ma20Slope?:number|null; ma60Slope?:number|null; ma120Slope?:number|null; aboveMa60Ratio60?:number|null; strongScore:number; isStrongTrend:boolean; isStrictStrongTrend:boolean; status:string; trendState?:string; trendScore:number; trendLevel:string; entryScore:number; entryLevel:string; overheatPenalty:number; marketEnvScore:number; marketEnvLevel:string; strategyScore:number; structureScore:number; momentumScore:number; slopeScore:number; positionScore:number; riskPenalty:number; ret120RankPct?:number|null; latestClose:number; latestAmount:number};
export type StrongTrendKline = {date:string; open:number; high:number; low:number; close:number; amount:number; pct_chg:number};
export type StrongTrendReview = {source:string; tradeDate:string; startDate:string; endDate:string; periodDays:number; updatedAt:string; top:number; summary:{poolCount:number; strictStrongCount?:number; looseStrongCount?:number; industryCount:number; topName:string; topRetYear:number; topScore:number; topStrategyScore?:number; marketEnvScore?:number; marketEnvLevel?:string}; items:StrongTrendItem[]; industryDistribution:{industry:string; count:number; avgRetYear:number; avgPeakRetYear?:number; avgScore:number}[]; kline:Record<string, StrongTrendKline[]>; statusRule:string; statusCounts?:Record<string,number>};
export type BaseOnBaseSignal = {signalDate:string; signalType:string; signalLabel:string; code:string; shortCode:string; name:string; industry:string; versions:string[]; versionLabel:string; entryDate:string; entryPrice:number; exitSignalDate?:string; exitDate:string; dateLabel?:string; valuationDate?:string; valuationClose?:number|null; isOpenPosition?:boolean; exitSignalLabel?:string; exitReason:string; exitReasonLabel:string; tradeReturn:number; maxReturnDuringHold:number; base2Days?:number|null; base2VolumeContract?:number|null; priorLegReturn?:number|null; hasExDividend:boolean};
export type BaseOnBaseReview = {updatedAt:string; days:number; startDate:string; endDate:string; summary:{signalCount:number; stockCount:number; v5Count:number; v6Count:number; bothCount:number}; items:BaseOnBaseSignal[]; kline:Record<string, StrongTrendKline[]>};
